/**
 * This code was generated by Builder.io.
 */
import React from 'react';

function TaskItem({ title }) {
  return (
    <div className="flex flex-col mt-2.5 w-full text-white max-w-[370px] first:mt-0">
      <div className="flex gap-5 justify-between px-6 py-5 rounded-2xl bg-neutral-800">
        <div className="self-start text-sm font-bold">
          {title}
        </div>
        <button className="overflow-hidden px-6 py-2.5 text-base font-semibold whitespace-nowrap bg-black rounded-lg">
          Go
        </button>
      </div>
    </div>
  );
}

export default TaskItem;