/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import TaskItem from './TaskItem';
import TaskProgress from './TaskProgress';

const socialTasks = [
  { title: 'Subscribe to our Telegram channel', type: 'action' },
  { title: 'Follow us on X', type: 'action' },
  { title: 'Follow us on Instagram', type: 'action' },
  { title: 'Subscribe to our YouTube channel', type: 'action' },
  { title: 'Boost Pink channel', type: 'action' },
  { title: 'Invite a friend', type: 'action' },
];

const progressTasks = [
  { title: 'Invite 3 friends', current: 0, target: 3 },
  { title: 'Invite 5 friends', current: 0, target: 5 },
  { title: 'Invite 10 friends', current: 0, target: 10 },
];

function TaskList() {
  return (
    <main className="flex overflow-hidden flex-col pt-5 mx-auto w-full bg-black max-w-[480px]">
      <header className="self-center text-xl font-semibold tracking-wide leading-none text-white">
        Daily Login
      </header>
      
      <section className="flex flex-col px-3 mt-5 w-full">
        <img 
          loading="lazy" 
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/b15af6878522d24ac8e61f0b21bbcb09f9ed25fbf284e7d9f4f4f004e994a5e9?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8" 
          alt="Daily login reward"
          className="object-contain self-center rounded-xl aspect-[6.76] w-[372px]" 
        />
        <button className="overflow-hidden self-center px-16 py-3 mt-5 w-full text-base font-semibold leading-none whitespace-nowrap rounded-lg bg-neutral-100 max-w-[350px] text-stone-900">
          Claim
        </button>
      </section>

      <h2 className="self-start mt-20 ml-2.5 text-xl font-semibold tracking-wide leading-none text-center text-white">
        Tasks
      </h2>

      <section className="flex flex-col px-2.5 pt-2.5 pb-4 mt-3 min-h-[736px]">
        {socialTasks.map((task, index) => (
          <TaskItem key={index} title={task.title} />
        ))}
        
        {progressTasks.map((task, index) => (
          <TaskProgress key={index} title={task.title} current={task.current} target={task.target} />
        ))}
      </section>

      <nav className="flex flex-col mt-8 w-full bg-black">
        <div className="flex overflow-hidden gap-2 px-2 py-px border-t border-zinc-500 border-opacity-10">
          <div className="flex shrink-0 w-32 bg-black h-[68px]" />
          <div className="flex shrink-0 w-32 bg-black h-[68px]" />
          <div className="flex shrink-0 w-32 bg-black h-[68px]" />
        </div>
      </nav>
    </main>
  );
}

export default TaskList;