/**
 * This code was generated by Builder.io.
 */
import { render, screen } from '@testing-library/react';
import ProgressIndicator from './ProgressIndicator';

describe('ProgressIndicator', () => {
  it('renders progress value correctly', () => {
    render(<ProgressIndicator />);
    const progressElement = screen.getByRole('progressbar');
    expect(progressElement).toHaveAttribute('aria-valuenow', '1');
    expect(progressElement).toHaveTextContent('1%');
  });
});