/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import NavigationBar from "./NavigationBar";

function InviteFriends() {
  return (
    <main className="flex flex-col items-center pt-96 mx-auto w-full bg-black max-w-[480px]">
      <h1 className="text-2xl font-semibold leading-6 text-center text-white w-[266px]">
        Invite friends to join and earn rewards together!
      </h1>
      <section className="flex gap-1.5 justify-center items-center mt-8 text-base font-semibold leading-none text-white whitespace-nowrap">
        <button className="flex flex-col self-stretch my-auto w-[100px]">
          <span className="overflow-hidden p-2.5 bg-rose-500 rounded-xl">
            Invite
          </span>
        </button>
        <img 
          loading="lazy" 
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/37ac0f6a41a6be3e7cb14d97be8e1aa476f271a1783bdd5d6a708e8ab531efbb?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8" 
          alt="Invite friends illustration"
          className="object-contain shrink-0 self-stretch my-auto aspect-[1.43] w-[50px]" 
        />
      </section>
      <NavigationBar />
    </main>
  );
}

export default InviteFriends;