/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function NavigationBar() {
  const navItems = [1, 2, 3];

  return (
    <nav className="flex flex-col self-stretch mt-96 w-full bg-black">
      <div className="flex overflow-hidden gap-2 px-2 py-px border-t border-zinc-500 border-opacity-10">
        {navItems.map((item) => (
          <div 
            key={item}
            className="flex shrink-0 w-32 bg-black h-[68px]"
            role="button"
            tabIndex={0}
          />
        ))}
      </div>
    </nav>
  );
}

export default NavigationBar;