/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import StatDisplay from "./StatDisplay";
import MiningButton from "./MiningButton";
import MiningSlot from "./MiningSlot";

function MiningStats() {
  const slots = [1, 2, 3];

  return (
    <main className="flex overflow-hidden flex-col pt-44 mx-auto w-full bg-black max-w-[480px]">
      <StatDisplay 
        iconSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/cd88f82f60bbc428513e9f65dbc71f28e0869162e2a2a520a9c604ac7189c1c9?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8"
        value="99,999,999"
      />
      <img 
        loading="lazy" 
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/5b4a910302e6f5cc2413e3860a6379ee1b26acf71b35272415262cad9b977e64?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8" 
        alt="Mining visualization"
        className="object-contain mt-6 w-full aspect-[0.92]" 
      />
      <MiningButton />
      <section className="flex gap-2.5 justify-center items-center mt-14 bg-black">
        <div className="flex overflow-hidden gap-2 self-stretch px-2 my-auto border-t border-zinc-500 border-opacity-10 w-[412px]">
          {slots.map((slot) => (
            <MiningSlot key={slot} />
          ))}
        </div>
      </section>
    </main>
  );
}

export default MiningStats;