/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function StatDisplay({ iconSrc, value }) {
  return (
    <div className="flex gap-2 justify-center items-center self-center text-4xl font-bold tracking-tighter leading-none text-white whitespace-nowrap">
      <img 
        loading="lazy" 
        src={iconSrc} 
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-square w-[35px]" 
      />
      <p className="self-stretch my-auto">{value}</p>
    </div>
  );
}

export default StatDisplay;