/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function ProgressIndicator() {
  return (
    <main className="flex flex-col justify-center items-center px-48 py-96 mx-auto w-full text-base font-semibold leading-none text-white whitespace-nowrap bg-black max-w-[480px]">
      <p className="px-0.5 w-5" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100">
        1%
      </p>
    </main>
  );
}

export default ProgressIndicator;
