/**
 * This code was generated by Builder.io.
 */
import { render, screen } from '@testing-library/react';
import MiningStats from '../MiningStats';

describe('MiningStats', () => {
  it('renders all components correctly', () => {
    render(<MiningStats />);
    
    expect(screen.getByText('99,999,999')).toBeInTheDocument();
    expect(screen.getByText('Mine')).toBeInTheDocument();
    expect(screen.getAllByRole('status')).toHaveLength(3);
  });
});