/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import TaskList from '../TaskList';

describe('TaskList', () => {
  it('renders the daily login header', () => {
    render(<TaskList />);
    expect(screen.getByText('Daily Login')).toBeInTheDocument();
  });

  it('renders the claim button', () => {
    render(<TaskList />);
    expect(screen.getByText('Claim')).toBeInTheDocument();
  });

  it('renders the tasks section', () => {
    render(<TaskList />);
    expect(screen.getByText('Tasks')).toBeInTheDocument();
  });
});