/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import TaskProgress from '../TaskProgress';

describe('TaskProgress', () => {
  it('renders the progress task correctly', () => {
    render(<TaskProgress title="Test Progress" current={0} target={5} />);
    expect(screen.getByText('Test Progress')).toBeInTheDocument();
    expect(screen.getByText('0/5')).toBeInTheDocument();
  });
});