/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';
import TaskItem from '../TaskItem';

describe('TaskItem', () => {
  it('renders the task title', () => {
    render(<TaskItem title="Test Task" />);
    expect(screen.getByText('Test Task')).toBeInTheDocument();
  });

  it('renders the go button', () => {
    render(<TaskItem title="Test Task" />);
    expect(screen.getByText('Go')).toBeInTheDocument();
  });
});