/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function TryAgain() {
  return (
    <main className="flex flex-col justify-center items-center px-20 py-96 mx-auto w-full text-xl font-semibold leading-none text-white bg-black max-w-[480px]">
      <section className="flex flex-col w-[86px]">
        <h1>Try Again</h1>
        <img 
          loading="lazy" 
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2d97eb4c732391da62f983a3b1126175465f691075b04cbef0811fd3a0765e4e?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8" 
          alt="Try again icon"
          className="object-contain self-center mt-11 aspect-[1.43] w-[50px]" 
        />
      </section>
    </main>
  );
}

export default TryAgain;