/**
 * This code was generated by Builder.io.
 */
import { render, screen } from '@testing-library/react';
import TryAgain from '../TryAgain';

describe('TryAgain', () => {
  it('renders the try again text', () => {
    render(<TryAgain />);
    expect(screen.getByText('Try Again')).toBeInTheDocument();
  });

  it('renders the try again icon', () => {
    render(<TryAgain />);
    const image = screen.getByAltText('Try again icon');
    expect(image).toBeInTheDocument();
    expect(image).toHaveAttribute('src', 'https://cdn.builder.io/api/v1/image/assets/TEMP/2d97eb4c732391da62f983a3b1126175465f691075b04cbef0811fd3a0765e4e?placeholderIfAbsent=true&apiKey=c7de70f57b014dd1a87bdc2dc51861a8');
  });
});