/**
 * This code was generated by Builder.io.
 */
import { render, screen } from '@testing-library/react';
import InviteFriends from '../InviteFriends';

describe('InviteFriends', () => {
  it('renders the main heading', () => {
    render(<InviteFriends />);
    expect(screen.getByText('Invite friends to join and earn rewards together!')).toBeInTheDocument();
  });

  it('renders the invite button', () => {
    render(<InviteFriends />);
    expect(screen.getByText('Invite')).toBeInTheDocument();
  });

  it('renders the illustration image', () => {
    render(<InviteFriends />);
    expect(screen.getByAltText('Invite friends illustration')).toBeInTheDocument();
  });
});