/**
 * This code was generated by Builder.io.
 */
import { render } from '@testing-library/react';
import NavigationBar from '../NavigationBar';

describe('NavigationBar', () => {
  it('renders navigation items', () => {
    const { container } = render(<NavigationBar />);
    const navItems = container.querySelectorAll('[role="button"]');
    expect(navItems).toHaveLength(3);
  });
});